### ISSUE TITLE
Plugin fails on release_stable_2018-04-22 because of changes on email validation

### ISSUE THREAD

**Issue by mobusi-dev-heads** [cosmocode/dokuwiki-plugin-publish#119]
The error goes as follows:

Fatal error: Uncaught Error: Call to undefined method EmailAddressValidator::check_email_address() in lib/plugins/publish/action/banner.php:93 Stack trace: #0 

Take a look at the related dokuwiki commit:
https://github.com/splitbrain/dokuwiki/commit/3d4e333534695cfd16101585f629d952020af0bf#diff-4075ffa520d3212204c5e5bfdc697fe9

**Comment by diegoscl** [comment]
+1 Same error here 😞

**Comment by s3zwirni** [comment]
+ Same error here
