### ISSUE TITLE
Report bug in "Publishing" when use option $conf['apr_mail_receiver'] 

### ISSUE THREAD

**Issue by strupifab** [cosmocode/dokuwiki-plugin-publish#126]
Hello,

I would like to give you a bug when I use the publishing plugin for dokuwiki.
There is a bug when filling the $ conf ['apr_mail_receiver'] parameter. When I put an email address, nothing works on the wiki.

Config file :  /lib/plugins/publish/conf/default.php
Ex parameter :  $conf['apr_mail_receiver'] = 'monadressemail@test.com';

Here is my configuration taking into account an email address : 
![plugin_config](https://user-images.githubusercontent.com/43041282/45168268-24605200-b1fb-11e8-8805-f39ab8765e6b.png)

Here is a picture before change :
![wiki_ok](https://user-images.githubusercontent.com/43041282/45168295-39d57c00-b1fb-11e8-95ca-2e1499017f30.png)

and after filling the parameter:
![wiki_ko](https://user-images.githubusercontent.com/43041282/45168304-3b9f3f80-b1fb-11e8-9f43-0725d0430992.png)
We do not see anymore the contents of the test page nor the debug part :-(

Thank you in advance for your return and correction.
Cordially
Fabien

**Comment by phy25** [comment]
Hi, are you sure you can receive other emails from DokuWiki, like password reset emails?

**Comment by strupifab** [comment]
Account configuration is done via an ad.
When I set the $ conf ['apr_mail_receiver'] variable to either the file or the admin page, nothing works on the wiki. The problem may come from elsewhere, but I bug it by customizing the variable of this plugin :-(
When I approve a page, I receive the approval email. But I would like to be able to receive the email when a page is modified, not only when it is approved. This action is possible with the variable 'apr_mail_receiver' but not functional for me.

**Comment by lukaspour** [comment]
I can confirm the same bug. When I fill in any email for "apr_mail_receiver" all content disappears from wiki - just requests for approve remain. 

DokuWiki version: 2018-04-22a

Publish plugin installed via extension manager in version 2019-01-10

I am using latest docker image: https://hub.docker.com/r/mprasil/dokuwiki

**Comment by bvdbos** [comment]
Dokuwiki 2018.04.22-0122 is the version used on Synology, together with PHP7.0. With the latest version of Publish (19-06-2019) this error is thrown...
![afbeelding](https://user-images.githubusercontent.com/1064079/71589454-3c14c580-2b25-11ea-9786-46c7b614822b.png)

**Comment by jlssmt** [comment]
> Dokuwiki 2018.04.22-0122 is the version used on Synology, together with PHP7.0. With the latest version of Publish (19-06-2019) this error is thrown...
> ![afbeelding](https://user-images.githubusercontent.com/1064079/71589454-3c14c580-2b25-11ea-9786-46c7b614822b.png)

Confirm this bug.
If I delete the problem lines I still won't get a mail.
