### ISSUE TITLE
Causes dokuwiki to fail to load after upgrade to hogfather

### ISSUE THREAD

**Issue by gw72** [cosmocode/dokuwiki-plugin-publish#144]
Following upgrade to hogfather dokuwiki fails to load giving an html 500 error. The log file shows:

PHP Fatal error:  Declaration of action_plugin_publish::register(&$controller) must be compatible with dokuwiki\\Extension\\ActionPlugin::register(Doku_Event_Handler $controller) in .../lib/plugins/publish/action.php on line 0 

Latest version of plugin was installed before upgrade

**Comment by phy25** [comment]
You can create a patch by https://www.patreon.com/posts/declaration-be-20638123

**Comment by annda** [comment]
The error suggests that there are leflovers from an ancient version of the plugin. The file causing the error no longer exists but it was never deleted on your system. Just reinstalling the plugin instead of updating should fix it.
