### ISSUE TITLE
'Approve' checkbox missing from page sections

### ISSUE THREAD

**Issue by darthWes** [cosmocode/dokuwiki-plugin-publish#153]
In the '2019-06-19' version of the publish plugin, each section of a page can be approved/edited individually.

In the current '2021-02-18' version of the plugin, each page must be approved as a whole, and no individual section can be approved.

To reproduce:

Create a new page using:

====== - Section 1 ======
This is test text for section 1.

====== - Section 2 ======
This is the test text for section 2.

====== - Section 3 ======
This is the text for section 3.

1. When you hit the 'edit' button on any section (not the entire page), and you have appropriate permissions, there should be an Approve checkbox at the bottom of the textarea that was used in conjunction with save button.

In the '2021-02-18' version (Hogfather version), the checkbox disappears and now you can only mass-accept edits on the page as a whole.

We liked the old approve checkbox and the ability to edit the page section by section.

I have done enough research that I know this is how the publish plugin is behaving; if this was intended, it is very difficult to find out when or why.  I searched through all the documents that I think I needed to search through.  I asked on the forums, and no one seems to know there either.  My guess, therefore, is that this was an unintended bug.

Thanks.

**Comment by splitbrain** [comment]
See https://forum.dokuwiki.org/d/19015-publish-plugin-sections-no-longer-published-as-units/9 the publish plugin never approved individual sections.
