### ISSUE TITLE
[APPROVALS] doesn't show subfolders

### ISSUE THREAD

**Issue by Sleinmaster** [cosmocode/dokuwiki-plugin-publish#39]
I have set publish only for one namespace (Erbauer) Erbauer and all it's subfolders show the banners and I also can approve all of the sites there.

On my page where I set the [APPROVALS] I'm only able to see the sites that are directly in Erbauer but none in the subfolders (which also have the banners).

**Comment by chtiland** [comment]
Works fine !

Thanks ;)
