### ISSUE TITLE
no sides to approve but there are someone

### ISSUE THREAD

**Issue by MaikLoewe** [cosmocode/dokuwiki-plugin-publish#66]
Hi,

I got a DokuWiki [2015-08-10a "Detritus"] running under Microsoft IIS 7.5.

I have some sites to approve but my page with the [APPROVALS] tag say's there are no sides to approve. I tried some setting within the name space option under the configuration but nothing helps.

At the moment both options "apr_namespaces" and "no_apr_namespaces" are empty.

I also tried to restart the page inside the IIS and use a other browser to avoid cache problems.
I just generate a new page with the [APPROVALS] tag, that doesn't help too.

I know that publish isn't in the in compatibility list of Detritus but maybe you can tell me if you know something about that issues or if you can reproduce the behaviour.

Best regards

**Comment by KwaKbs** [comment]
I have the same Problem with [APPROVALS] in Detritus.

Thanks for your reply
