### ISSUE TITLE
(not a bug) publish & data plugin

### ISSUE THREAD

**Issue by oschwab** [cosmocode/dokuwiki-plugin-publish#78]
Hello ,

Does anyone see a mean to use _Publish_ with the _Data_ [plugin](https://www.dokuwiki.org/plugin:data) in order to display approval status of a document in _Data_ output (datable and/or datalist) ?

Thanks by advance

**Comment by splitbrain** [comment]
no. the data plugin works on the most current revision on a page only. its not compatible with the way publish works.

(btw. this is not a forum)

**Comment by oschwab** [comment]
Thanks for fast reply.
Sorry for posting here but bottom of your plugin page on dokuwiki says:

_Questions can be asked in the forum or the bugtracker. _

Rgds,
