### ISSUE TITLE
lang/fr/lang.php "a été Approuvée"

### ISSUE THREAD

**Issue by cpamcom** [cosmocode/dokuwiki-plugin-publish#85]
line 13:
`$lang['apr_approved']          = 'Cette version (%s) à été <em>Approuvé</em> par %s.';`

should be:

`$lang['apr_approved']          = 'Cette version (%s) a été <em>Approuvée</em> par %s.';`

**Comment by splitbrain** [comment]
please use https://translate.dokuwiki.org to send an update.
