### ISSUE TITLE
PHP Warning: Illegal string offset

### ISSUE THREAD

**Issue by cziehr** [cosmocode/dokuwiki-plugin-publish#95]
In the error-log of my apache-server, the following line appears often:

`PHP Warning:  Illegal string offset '_elem' in /var/www/html/wiki/lib/plugins/publish/action/revisions.php on line 37`

It must have to do with arrays, but I don't know what to do exactly.

EDIT: it seems that this issue was investigated yet at https://github.com/cosmocode/dokuwiki-plugin-publish/pull/35

**Comment by annda** [comment]
Fixed in #102
